import { NextRequest, NextResponse } from 'next/server';
import { connectDB } from '@/lib/db';
import QRRecord from '@/models/QRRecord';

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ uniqueCode: string }> }
) {
  try {
    // FIXED: Awaiting the dynamic params Promise before extracting properties
    const resolvedParams = await params;
    const { uniqueCode } = resolvedParams;

    await connectDB();

    // 1. Fetch QR Record by uniqueCode
    const qrRecord = await QRRecord.findOne({ uniqueCode: uniqueCode.toUpperCase() });

    // 2. Handle Not Found (404)
    if (!qrRecord) {
      const acceptHeader = req.headers.get('accept') || '';
      if (acceptHeader.includes('application/json')) {
        return NextResponse.json(
          {
            error: true,
            code: 'QR_NOT_FOUND',
            message: 'This QR code was not generated by TalentYug systems or does not exist.',
            statusCode: 404,
          },
          { status: 404 }
        );
      }

      return new NextResponse(
        `<!DOCTYPE html>
        <html>
          <head><title>QR Not Found - TalentYug</title></head>
          <body style="font-family: sans-serif; display: grid; place-content: center; height: 100vh; text-align: center; background: #f8fafc;">
            <h1 style="color: #ef4444;">404 - Invalid QR Code</h1>
            <p>This QR code was not generated by TalentYug systems or does not exist.</p>
          </body>
        </html>`,
        { status: 404, headers: { 'Content-Type': 'text/html' } }
      );
    }

    // 3. Handle Deactivated QR Code
    if (!qrRecord.isActive) {
      const acceptHeader = req.headers.get('accept') || '';
      if (acceptHeader.includes('application/json')) {
        return NextResponse.json(
          {
            error: true,
            code: 'QR_DEACTIVATED',
            message: 'QR code has been deactivated',
            statusCode: 400,
          },
          { status: 400 }
        );
      }

      return new NextResponse(
        `<!DOCTYPE html>
        <html>
          <head><title>QR Deactivated - TalentYug</title></head>
          <body style="font-family: sans-serif; display: grid; place-content: center; height: 100vh; text-align: center; background: #f8fafc;">
            <h1 style="color: #f59e0b;">QR Code Deactivated</h1>
            <p>This QR code has been deactivated by the administrator and is no longer active.</p>
          </body>
        </html>`,
        { status: 400, headers: { 'Content-Type': 'text/html' } }
      );
    }

    // 4. Extract Client IP & User-Agent for Scan Logging
    const clientIp =
      req.headers.get('x-forwarded-for')?.split(',')[0] ||
      req.headers.get('x-real-ip') ||
      '127.0.0.1';
    const userAgent = req.headers.get('user-agent') || 'Unknown';

    // 5. Atomic Update: Increment scanCount & append scanLog
    qrRecord.scanCount += 1;
    qrRecord.scanLogs.push({
      scannedAt: new Date(),
      ipAddress: clientIp,
      userAgent: userAgent,
    });
    await qrRecord.save();

    // 6. Handle API Response (JSON)
    const acceptHeader = req.headers.get('accept') || '';
    if (acceptHeader.includes('application/json')) {
      return NextResponse.json({
        status: 'verified',
        uniqueCode: qrRecord.uniqueCode,
        label: qrRecord.label,
        originalUrl: qrRecord.originalUrl,
        createdAt: qrRecord.createdAt,
        scanCount: qrRecord.scanCount,
        isActive: qrRecord.isActive,
      });
    }

    // 7. Handle Browser Scan (HTML Page with Redirect)
    const html = `<!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="refresh" content="2;url=${qrRecord.originalUrl}" />
        <title>Verifying QR - TalentYug</title>
        <style>
          body {
            font-family: system-ui, -apple-system, sans-serif;
            background-color: #0f172a;
            color: #f8fafc;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
          }
          .card {
            background: #1e293b;
            padding: 2rem;
            border-radius: 12px;
            box-shadow: 0 10px 25px rgba(0,0,0,0.5);
            text-align: center;
            max-width: 400px;
          }
          .badge {
            background: #22c55e;
            color: white;
            padding: 4px 12px;
            border-radius: 999px;
            font-size: 0.875rem;
            font-weight: 600;
          }
          a {
            color: #38bdf8;
            text-decoration: none;
            font-weight: 500;
          }
        </style>
      </head>
      <body>
        <div class="card">
          <span class="badge">Verified System QR</span>
          <h2 style="margin-top: 1rem;">${qrRecord.label || 'QR Verified'}</h2>
          <p style="color: #94a3b8; font-size: 0.9rem;">Code: <strong>${qrRecord.uniqueCode}</strong></p>
          <p style="margin-top: 1.5rem;">Redirecting to target destination in 2 seconds...</p>
          <p><a href="${qrRecord.originalUrl}">Click here if you are not redirected automatically</a></p>
        </div>
      </body>
    </html>`;

    return new NextResponse(html, {
      status: 200,
      headers: { 'Content-Type': 'text/html' },
    });
  } catch (error: unknown) { // FIXED: Banned explicit 'any' type changed to unknown context
    console.error('Error during verification:', error);
    
    const errorMessage = error instanceof Error ? error.message : 'Failed to verify QR code';

    return NextResponse.json(
      {
        error: true,
        code: 'INTERNAL_SERVER_ERROR',
        message: errorMessage,
        statusCode: 500,
      },
      { status: 500 }
    );
  }
}
